### ISSUE TITLE
[Enhancement] Allow mixing and matching Men.pak and Men2.pak from different themes

### ISSUE THREAD

**Issue by DraconicNEO** [Xpl0itU/theme-manager#4]
I think it would be nice if we had the ability to choose to install the Men.pak and Men2.pak from separate themes in the app in order to have more customization in how themes are installed.

**Comment by Xpl0itU** [comment]
Just put the men.pack and the men2.pack files mixed in the same folder

**Comment by DraconicNEO** [comment]
> Just put the men.pack and the men2.pack files mixed in the same folder

I felt like it would be easier to have the option to select the Files from individual themes rather than requiring the user to swap files around, after all swapping files for theme customization was one of the major downsides to Rosalina, right?

**Comment by Xpl0itU** [comment]
I don’t see why you would want to mix files, anyways, I’m not doing that

**Comment by DraconicNEO** [comment]
> I don’t see why you would want to mix files, 

In case someone wants to create a two toned look, or in the cases where some themes do things to the cursor.

> anyways, I’m not doing that

Okay, thanks anyway.

**Comment by ghost** [comment]
@DraconicNEO if you genuinely want this feature for yourself then the project is open sourced and honestly pretty easy to read / edit.

The project as of now automatically reads from the "themes" directory, then accepts user input to see which folder to read for both Men.pack and Men2.pack in the same instruction. All you have to do is separate that into two different instructions

for example it automatically searches "themes" and displays the existing folders, correct? Instead of selecting one of those displayed folder to select both .pack files - have it only select one. Then move on to the second instruction to pick another. 

Pseudo example:
Instruction 1 = input(path('')):
 ‎‎‎‎‎‎‎‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎select Men.pack

Then after the two are selected it would go on to install like normal.

This is grossly oversimplified so take it with a grain of salt. (also not really a needed feature at all, since if you wanted to mix you could just move the mixed files into a new folder and install like that. You could even use WiiU-Shell if you're too lazy to take out your SD Card)

**Comment by DraconicNEO** [comment]
> @DraconicNEO if you genuinely want this feature for yourself then the project is open sourced and honestly pretty easy to read / edit.
> 

I just thought this was a good idea that people would like, I mean other menu themer apps on different platforms have similar features to that which allow you to select different themes for different parts of the system menu (i.e. on Switch they have the option to use different themes in different places). 


I'm not going to take the time to implement a feature for myself since I'll just have to re-implement it for every patch and bugfix that gets released. I could do it in a pull request but again it doesn't seem like he wants this feature so I'm hesitant to put in work for a pull request that might not get accepted.

> also not really a needed feature at all, since if you wanted to mix you could just move the mixed files into a new folder and install like that. You could even use WiiU-Shell if you're too lazy to take out your SD Card)

No but it would likely be something that people would like. I'm not doing it just for myself though because that's not why I made this issue. Seems like you think I just made this issues as some form of begging, maybe that's not the case and you're just trying to help but it definitely gives off that vibe.

**Comment by ghost** [comment]
Oh no I'm not trying to be condescending at all. I was just simply offering a way you could make your idea since it won't be added to the original repo; so I'm sorry if it came off differently.

But it was a genuine suggestion - people often make forks of open-sourced projects to add their own features, and with that in mind even if updates are pushed you don't _need_ to update your fork as well (although it would probably be beneficial to). Anyways the tool is pretty solid at the moment with stuff like CRC checking and prevention of installing corrupted themes so it's possible that your fork could just live on it's own.

**Comment by DraconicNEO** [comment]
> Oh no I'm not trying to be condescending at all. I was just simply offering a way you could make your idea since it won't be added to the original repo; so I'm sorry if it came off differently.
> 

No worries, I probably just misinterpreted it because it's been happening a lot lately.

> But it was a genuine suggestion - people often make forks of open-sourced projects to add their own features, and with that in mind even if updates are pushed you don't _need_ to update your fork as well (although it would probably be beneficial to). Anyways the tool is pretty solid at the moment with stuff like CRC checking and prevention of installing corrupted themes so it's possible that your fork could just live on it's own.

I've noticed that when people make forks that are made obsolete by the master it makes people less likely to use it, it's true that I wouldn't necessarily have to update it every time they do but if I don't they might start updating theirs to drive people away from mine I have actually heard of developers doing this and it seems really Petty it's like a pissing contest.

There's only one way that I will ever make this fork and that is if XploitU ever goes completely inactive for a very long period of time with no sign of ever coming back. I'm not cut out for maintaining a fork forever and we both know that people aren't going to use it if it's not updated (it's literally actively discouraged in and by the community).
